name = "OrbisChessEngine"
uuid = "2eacc985-a635-41e1-b67f-45fa7ceb5b4d"
version = "0.3.0-dev"
authors = ["Bjarke Hautop <bjarke.hautop@gmail.com> and contributors"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Aqua = "0.8.14"
Distributions = "0.25"
Preferences = "1.5.1"
Random = "1.6"
StaticArrays = "1.9.15"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
