name = "OrbisChessEngine"
uuid = "2eacc985-a635-41e1-b67f-45fa7ceb5b4d"
version = "0.2.2"
authors = ["Bjarke Hautop <bjarke.hautop@gmail.com> and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Aqua = "0.8.14"
CairoMakie = "0.15.6"
Colors = "0.13.1"
Distributions = "0.25"
FileIO = "1.17.0"
Images = "0.26.2"
Random = "1.6"
StaticArrays = "1.9.15"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
